export const DASHBOARD_ROUTE ="/dashboard"
export const SIGNIN_ROUTE ="/"
export const CREATE_ROUTE ="/Create"
export const CREATE_FORM ="/CreateEvent/:venue/:date"
export const INVOICE_ROUTE ="/invoice"
export const ADMIN_DASHBOARD = "/admindashboard"
export const ALL_FARMS = "/farms"